spring:
  application:
    name: product
  datasource:
    url: jdbc:postgresql://localhost:5433/products
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    config:
        enabled: false
server:
  port: 9700